version: "3.5"

services:
  postgres:
    image: postgres:11.5-alpine
    environment:
      - POSTGRES_LOGGING=true
      - POSTGRES_DB_FILE=/run/secrets/postgres_db
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres_password
      - POSTGRES_USER_FILE=/run/secrets/postgres_user
    secrets:
      - postgres_password
      - postgres_user
      - postgres_db
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    restart: on-failure

  cardano-node:
    image: inputoutput/cardano-node:master
    environment:
      - NETWORK=${NETWORK}
    volumes:
      - cardano-node:/data

  cardano-db-sync:
    image: inputoutput/cardano-db-sync:master
    environment:
      - NETWORK=${NETWORK}
    depends_on:
      - cardano-node
      - postgres
    secrets:
      - source: pgpass
        target: /config/pgpass
    volumes:
      - cardano-node:/data
    restart: on-failure

  cardano-explorer-api:
    image: inputoutput/cardano-explorer-api:master
    depends_on:
      - postgres
    secrets:
      - source: pgpass
        target: /config/pgpass
    ports:
      - 8100:8100

  cardano-submit-api:
    image: inputoutput/cardano-submit-api:master
    environment:
      - NETWORK=${NETWORK}
    depends_on:
      - cardano-node
    volumes:
      - cardano-node:/data
    ports:
      - 8101:8101
    restart: on-failure

secrets:
  postgres_db:
    file: ./config/postgres_db
  postgres_password:
    file: ./config/postgres_password
  postgres_user:
    file: ./config/postgres_user
  pgpass:
    file: ./config/pgpass

volumes:
  postgres:
  cardano-node:
