resolver: ./snapshot.yaml
compiler: ghc-8.6.5

allow-newer: true

packages:
  - explorer-api
  - submit-api

extra-deps:
  - git: https://github.com/input-output-hk/cardano-db-sync
    commit: 5407a064d4462712a5641295e93cf94d906bd897
    subdirs:
      - cardano-db
      - cardano-db-sync

  - git: https://github.com/input-output-hk/cardano-crypto
    commit: 2547ad1e80aeabca2899951601079408becbc92c

ghc-options:
  cardano-explorer-api: -Wall -Werror -fwarn-redundant-constraints
  cardano-submit-api:   -Wall -Werror -fwarn-redundant-constraints

nix:
  shell-file: nix/stack-shell.nix
